#!/usr/bin/env python3

import sys
import json
import os
import subprocess
import urllib.request

DB_PATH = os.path.expanduser("~/.waypoints-cli/data/waypoints.json")
COMMANDS = {"add", "get", "delete", "list", "help", "stale", "uninstall"}
RESERVED = COMMANDS

def load_db():
    if not os.path.exists(DB_PATH):
        return {}
    with open(DB_PATH, "r") as f:
        return json.load(f)
    
def save_db(db):
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    with open(DB_PATH, "w") as f:
        json.dump(db, f, indent=2)

def get_version():
    path = os.path.expanduser("~/.waypoints-cli/VERSION")
    if not os.path.exists(path):
        return "0.0.0"
    return open(path).read().strip()

def get_latest_version():
    try:
        url = "https://raw.githubusercontent.com/Yashom-Kapoor/Waypoints-CLI/main/waypoints/VERSION"
        with urllib.request.urlopen(url) as response:
            return response.read().decode().strip()
    except Exception:
        return "x.x.x"

def update(latest_version):
    INSTALL_CMD = "curl -sSL https://raw.githubusercontent.com/Yashom-Kapoor/Waypoints-CLI/main/install.sh | bash"
    subprocess.run(INSTALL_CMD, shell=True)

    print(f"Update complete. You are now on version {latest_version}")

def main():
    args = sys.argv[1:]
    db = load_db()

    if not "home" in db.items():
        db["home"] = os.path.expanduser("~")
        save_db(db)

    if len(args) == 0 or args[0] == "help":
        print(f"""
Welcome to Waypoints! :)
Your lightweight CLI waypoint helper
Author: Yashom Kapoor
Version: {get_version()}
=====================================

Waypoint Navigation:
  <name>            Navigate to waypoint <name>
  home              Navigate to home (~)

Waypoint Modification:
  add <path> <name> Save a directory as <name>
  get <name>        Print saved path
  delete <name>     Remove saved waypoint

Utility:
  list              Show all waypoints

Stale Paths:
  stale             List all stale paths
  stale -d          Delete all stale paths

Info:
  -v, --version     Show Waypoints CLI version

Installations:
  update            Update Waypoints
  uninstall         Uninstall Waypoints
""")
        sys.exit(67)
        return
    
    command = args[0]

    if command == "add":
        if len(args) < 3:
            print("Usage: wp add <path> <name>")
            sys.exit(67)
            return
        
        name = args[2].strip().lower()
        path = os.path.abspath(os.path.expanduser(args[1]))

        if not os.path.exists(path):
            print(f"Path does not exist: {path}")
            sys.exit(67)
            return
            
        if name in RESERVED:
            print(f"'{name}' is a reserved command name. Choose a different waypoint name.")
            sys.exit(67)
            return

        if name in db:
            reply = input(f"{name} already exists. Replace it? (Y/N): ").strip()

            if not reply or reply[0].lower() != "y":
                print("Cancelled")
                sys.exit(67)
                return

        db[name] = path
        save_db(db)

        print(f"Saved {name} -> {path}")

    elif command == "get":
        if len(args) == 1:
            print("Usage: wp get <name>")
            sys.exit(67)
            return
        
        name = args[1]
        print(db.get(name, "Not found"))

    elif command == "list":
        for k, v in db.items():
            print (k, "->", v)

    elif command == "delete":
        if len(args) == 1:
            print("Usage: wp delete <name>")
            sys.exit(67)
            return

        name = args[1]

        if name in db:
           del db[name]
           save_db(db)
           print(f"Deleted {name}")

    elif command == "stale":
        stale = []

        for name, path in db.items():
            if not os.path.exists(path):
                stale.append([name, path])
        
        if "-d" in args:
            for pair in stale:
                del db[pair[0]]
            save_db(db)
            print(f"Deleted {len(stale)} stale waypoints")

        else:
            if not stale:
                print("No stale waypoints")
            else:
                "Stale waypoints:"
                for pair in stale:
                    print(pair[0], "->", pair[1])

    elif command == "-v" or command == "--version":
        current_version = get_version()
        print(f"Waypoints {current_version}")

    elif command == "update":
        latest_version = get_latest_version()
        current_version = get_version()
        if (latest_version == current_version):
            print("Already up to date.")
        else:
            print(f"Updating...")
            update(latest_version)

    elif command == "__complete":
        prefix = args[2]
        prefix = prefix.strip().lower()
        command = args[1]

        if (command == "get" or command == "delete"):
            options = list(db.keys())
        else:
            options = list(db.keys()) + list(COMMANDS)
        
        matches = [item for item in options if item.startswith(prefix)]

        for match in matches:
            print(match)

    elif command in db:
        print(db.get(command, ""))
        sys.exit(0) # 0 = shell should cd to this folder
        return

    elif command == "uninstall":        
        reply = input("Are you sure you want to uninstall Waypoints CLI? (Y/N): ").strip()

        if not reply or reply[0].lower() != "y":
            print("Ok!")
            sys.exit(67)
            return
        else:
            subprocess.run(["bash", os.path.expanduser("~/.waypoints-cli/uninstall.sh")])

    else:
        print("Unknown command")

    sys.exit(67) # 67 = shell should do nothing


if __name__ == "__main__":
    main()
